### ISSUE TITLE
Mark YSSegmentedControl as Public

### ISSUE THREAD

**Issue by mehfuzh** [yemeksepeti/YSSegmentedControl#1]
In order to use YSSegmentedControl outside of Pods project i had to mark the class as public

**Comment by drewpitchford** [comment]
Need to hook up your delegate to actually call the methods.

**Comment by prohybe** [comment]
Hello guys!
I have successfully installed this project, but how can I actually put it to work? I am still learning xcode.. Can someone help me? Thanks

**Comment by cemolcay** [comment]
project updated lastest swift syntax and fixed delegation errors.
